name: learn-github-actions
run-name: ${{github.actor}} is learning the Github Actions
on: [push]
jobs:
   check-bats-version:
     runs-on: ubuntu-latest
     steps:
        - name: My first step - check out repository
          uses: actions/checkout@v4
         # This step references the directory that contains the action.
        - name: Use local hello-world-action
          uses: ./.github/actions/hello-world-action   

